name: Build

on: ['push']
#  push:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: run the tests
        run: pnpm test:coverage

      - name: arweave-bundler dry run
        uses: ./
        with:
          directory: build/
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}
          dry-run: true
          network: arweave.net
