name: Semantic Release Workflow

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: run the tests
        run: pnpm test:coverage

      - name: arweave-bundler dry run
        uses: ./
        with:
          directory: build/
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}
          dry-run: true
          network: arweave.net

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

