name: release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: run the tests
        run: pnpm test:coverage

      - name: build the action
        run: pnpm build

      - name: get wallet address
        uses: ./
        with:
          command: address
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}

      - name: simulate an upload
        uses: ./
        with:
          command: upload
          directory: build/
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}
          dry-run: true
          network: arweave.net

      - name: set the ArNS record
        uses: ./
        with:
          command: set
          manifest-id: EvHa663GhcAFh1cNbioclep9S0goMwWBQgGFyoRyIxk
          ant-address: vyti5Zsqbk25hTsYrIkePpwKK7jdiXNDHRKa09die3g
          private-key: ${{secrets.ARWEAVE_PRIVATE_KEY}}
          dry-run: true
          network: arweave.net        

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

